name: code-checkout
on: [push]
jobs:
  checkout:
   runs-on: ubuntu-latest
   steps:
     - name: git code checkout
       uses: actions/checkout@v5
     - name: list files
       run: cd/.github/workflows | ls -la